import Link from "next/link"; import {ArrowUpRight, Bell, ChevronRight, Grid2X2, Home, Library, Search, Settings, UsersRound, X} from "lucide-react"; import type {ReactNode} from "react";
export const Button=({children,variant="dark"}:{children:ReactNode;variant?:"dark"|"light"|"cyan"})=><button className={`inline-flex items-center gap-2 rounded-full px-5 py-3 text-sm font-semibold transition ${variant==="dark"?"bg-ink text-white hover:bg-indigo":variant==="cyan"?"bg-cyan text-ink":"bg-white text-ink hover:bg-mist"}`}>{children}</button>;
export const Badge=({children}:{children:ReactNode})=><span className="rounded-full bg-white/70 px-3 py-1 text-[11px] font-bold uppercase tracking-[.1em] text-ink/60">{children}</span>;
export const Avatar=({name,color="#E2F5F3"}:{name:string;color?:string})=><span style={{backgroundColor:color}} className="grid h-9 w-9 place-items-center rounded-full text-xs font-bold">{name}</span>;
export const Card=({children,className=""}:{children:ReactNode;className?:string})=><section className={`surface ${className}`}>{children}</section>;
export const SearchBox=()=> <label className="flex h-11 items-center gap-2 rounded-full bg-mist px-4 text-ink/50"><Search size={17}/><input aria-label="Search" placeholder="Search your workspace" className="w-full bg-transparent text-sm outline-none placeholder:text-ink/45"/></label>;
export const EmptyState=({title,copy}:{title:string;copy:string})=><div className="grid min-h-[430px] place-items-center rounded-[32px] bg-mist p-8 text-center"><div><div className="mx-auto mb-5 h-16 w-16 rounded-full bg-ice/70"/><h2 className="text-2xl font-semibold tracking-tight">{title}</h2><p className="mx-auto mt-2 max-w-sm text-sm leading-6 text-ink/60">{copy}</p></div></div>;
export const Progress=({value}:{value:number})=><div className="h-1.5 w-full overflow-hidden rounded-full bg-ink/10"><div className="h-full rounded-full bg-cyan" style={{width:`${value}%`}}/></div>;
export function Sidebar(){const nav=[{href:"/home",label:"Home",icon:Home},{href:"/explore",label:"Explore",icon:Grid2X2},{href:"/library",label:"Library",icon:Library},{href:"/clients",label:"Clients",icon:UsersRound}];return <aside className="fixed inset-y-0 left-0 z-20 hidden w-[212px] flex-col border-r border-ink/8 bg-[#fbfcfb] px-5 py-8 md:flex"><Link href="/home" className="mb-14 text-xl font-bold tracking-[-.08em]">OPALITE<span className="text-cyan">.</span></Link><nav className="space-y-1">{nav.map(({href,label,icon:Icon})=><Link key={href} href={href} className="flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-medium text-ink/60 transition hover:bg-mist hover:text-ink"><Icon size={18}/>{label}</Link>)}</nav><div className="mt-auto"><Link href="/settings" className="flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-medium text-ink/60 hover:bg-mist hover:text-ink"><Settings size={18}/>Settings</Link><div className="mt-5 flex items-center gap-2 border-t border-ink/8 pt-5"><Avatar name="RS" color="#A4CBE3"/><span className="text-sm font-medium">Roy Su</span></div></div></aside>}
export function AppShell({children}:{children:ReactNode}){return <><Sidebar/><main className="min-h-screen px-5 py-7 md:ml-[212px] md:px-10 lg:px-14">{children}</main></>}
export const PageHeader=({eyebrow,title,children}:{eyebrow:string;title:string;children?:ReactNode})=><header className="mb-10 flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow mb-3">{eyebrow}</p><h1 className="page-title">{title}</h1></div>{children}</header>;
export const SectionHead=({title,action}:{title:string;action?:string})=><div className="mb-4 flex items-center justify-between"><h2 className="text-xl font-semibold tracking-[-.035em]">{title}</h2>{action&&<button className="flex items-center gap-1 text-sm font-semibold">{action}<ChevronRight size={16}/></button>}</div>;
export {ArrowUpRight,Bell,X};
